### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### use balance account
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "1000000001",
  "amount": 2000
}

### use balance2 account
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "1000000000",
  "amount": 2000
}

### cancel balance account
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "74448c151d3344b7be78a60ebcfb5cbb",
  "accountNumber": "1000000003",
  "amount": 2000
}

### query transaction
GET http://localhost:8080/transaction/db9864ad11db476e92d3d1893ffa251d
